[project]
name = "randomized-svd-paper"
version = "0.1.0"
description = "Randomized SVD paper for the DAT390 course."
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "ipykernel>=7.1.0",
    "matplotlib>=3.10.7",
    "numpy>=2.3.3",
    "scipy>=1.16.3",
]
